---
- name: Configurar servidor de banco de dados
  hosts: db01
  remote_user: vagrant
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql
      become: yes