- name: run ansible galaxy
  local_action: command ansible-galaxy install -r requirements.yml --ignore-errors
  become: yes
- name: Upgrade de todos os pacotes do s.o
  become: yes
  apt:
    update_cache: yes
- name: Instalacao do git client
  become: yes
  apt:
    name: git
    state: latest
- name: Configurar hosts lab ansible
      lineinfile: 
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
        - 192.168.56.2 control-node
        - 192.168.56.3 app01
        - 192.168.56.4 db01