services:
  jenkins:
    build:
      context: ./
      dockerfile: ./jenkins/Dockerfile
    container_name: jenkins-local
    privileged: true
    user: root
    ports:
      - 9090:8443 # ssl
      - 50000:50000
    environment:
      JENKINS_OPTS: "-Xmx2048m --httpPort=8080 --httpsPort=8443 --httpsKeyStore=/var/ssl/keystore.jks --httpsKeyStorePassword=123456"
      JENKINS_HTTPS_KEYSTORE: "/var/ssl/keystore.jks"
      JENKINS_HTTPS_KEYSTORE_PASSWORD: "123456" # senha-em-texto-não criptografado-para-armazenamento-de-chaves
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/ssl:/var/ssl
    restart: always
    networks:
      - sonar-jenkins-network
    depends_on:
      - sonarqube
  sonarqube:
    build:
      context: .
      dockerfile: ./sonar/Dockerfile
    image: local/sonarqube:latest
    container_name: sonar-local
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    user: 1000:1000
    ports:
      - "9000:9000"
    networks:
      - sonar-jenkins-network
      - sonar-db-network
  db:
    image: postgres:12.20-alpine3.20
    container_name: postegres-sonar-local
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - sonar-db-network
  nexus:
    image: sonatype/nexus3:3.73.0-java17-alpine
    container_name: nexus-local
    user: root
    ports:
      - "8094:8094"
      - "8123:8123"
    volumes:
      - nexus-data:/nexus-data
      - ./nexus/ssl:/nexus-data/etc/ssl
      - ./nexus/etc/nexus.properties:/nexus-data/etc/nexus.properties
      - ./nexus/jetty/jetty-https.xml:/opt/sonatype/nexus/etc/jetty/jetty-https.xml
    environment:
      NEXUS_SECURITY_RANDOMPASSWORD: false  # Desabilitar senha aleatória na inicialização
      INSTALL4J_ADD_VM_PARAMS: "-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m"
    restart: unless-stopped
    networks:
      - sonar-jenkins-network
    depends_on:
      - sonarqube
      - jenkins

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
  nexus-data:

networks:
  sonar-jenkins-network:
  sonar-db-network: