Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = 'manager-k3s'
  config.vm.network "forwarded_port", guest: 8888, host: 8888
  config.vm.network "forwarded_port", guest: 4444, host: 4444
  config.vm.network "private_network", ip: "192.168.56.150"
  config.vm.provision "shell", path: "provision.sh"
  # Configurar a VM
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "5120"  # 5 GB de RAM
    vb.cpus = 4         # 4 CPUs
  end
end