Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.hostname = "app01"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "private_network", ip: "192.168.56.3"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", path: "provision.sh" 
end